# From Python to Numpy


In [32]:
import numpy as np

## 3. Anatomy of an array

Concepts covered:
- Memory layout
- View
- Copy
- Data type

In [24]:
Z = np.ones(4*1000000, np.float32)

In [25]:
Z1 = Z[:]
%timeit Z1[...] = 0

722 µs ± 30.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [26]:
Z2 = Z[:]
%timeit Z2.view(np.int8)[...] = 0

661 µs ± 25.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


The reason for such speedup are to be found in the internal numpy machinery and the compiler optimization.

### 3.2 Memory layout

An array is mostly a contiguous block of memory whose parts can be accessed using an indexing scheme

In [31]:
Z = np.arange(9).reshape(3, 3).astype(np.int8)
print(Z)
print(Z.itemsize)
print(Z.shape)
print(Z.ndim)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
1
(3, 3)
2
